### PR TITLE
Update explore function

### PR DESCRIPTION
**Pull request by khuynhthanhchiluyen**

### CODE REVIEW

**Comment by knonomura** [comment]
Oh, that's wonderful.

I guess explore function is one of functions since Grafana 6.0.
Which version of Grafana did you use ?
Thanks.

**Comment by khuynhthanhchiluyen** [comment]
I used Grafana 6.2

**Comment by knonomura** [comment]
I understand.
I'll check your PR.

**Comment by knonomura** [comment]
Thank you so much for your PR.
I merge it.

**Pull request merged**
